"""
提示词系统
"""
from .outline_prompts import OUTLINE_PROMPT, OUTLINE_VALIDATION_PROMPT
from .design_prompts import DESIGN_PROMPT, STYLE_GENES_PROMPT, CONSTITUTION_PROMPT
from .layout_repair_prompts import LAYOUT_INSPECTION_PROMPT, LAYOUT_REPAIR_PROMPT

__all__ = [
    'OUTLINE_PROMPT',
    'OUTLINE_VALIDATION_PROMPT',
    'DESIGN_PROMPT',
    'STYLE_GENES_PROMPT',
    'CONSTITUTION_PROMPT',
    'LAYOUT_INSPECTION_PROMPT',
    'LAYOUT_REPAIR_PROMPT'
]
